<?php

namespace Tests\Jobs;

use App\Jobs\GetGamesPlayed;
use App\Models\Player;
use App\Models\RankedGamesScannedUserIds;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Str;
use JetBrains\PhpStorm\NoReturn;
use Tests\TestCase;

class GetGamesPlayedTest extends TestCase
{
    use RefreshDatabase;

    const string ID = '6a00ef51505faf23e3cc420d';

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->contents = file_get_contents('tests/Jobs/Fixtures/GamesPlayed.html');
    }

    #[NoReturn]
    public function test_it_updates_rating_and_creates_rating_change()
    {
        $player = Player::factory()->create([
            'user_id' => Str::uuid()->toString(),
            'nmpz_rating' => 1000,
            'moving_rating' => 1000,
            'ranked_duels_played' => 0,
        ]);

        Http::fake([
            '*' => Http::response($this->contents),
        ]);

        new GetGamesPlayed(0)->handle();

        $this->assertDatabaseHas('players', [
            'user_id' => $player->user_id,
            'ranked_duels_played' => 219,
            'single_player_games_played' => 3,
            'unranked_duels_played' => 2,
            'ranked_team_duels_played' => 8,
            'unranked_team_duels_played' => 0,
        ]);
    }

    public function test_it_tracks_covered_ids()
    {
        $this->assertDatabaseEmpty('ranked_games_scanned_user_ids');

        $player = Player::factory()->create([
            'user_id' => self::ID,
            'nmpz_rating' => 1000,
            'moving_rating' => 1000,
            'ranked_duels_played' => 0,
        ]);

        Http::fake([
            '*' => Http::response($this->contents),
        ]);

        new GetGamesPlayed(0)->handle();

        $this->assertDatabaseHas('ranked_games_scanned_user_ids', [
            'user_ids' => json_encode([$player->user_id]),
        ]);
    }

    public function test_it_appends_new_ids()
    {
        $this->assertDatabaseEmpty('ranked_games_scanned_user_ids');

        $player = Player::factory()->create([
            'nmpz_rating' => 1000,
            'moving_rating' => 1000,
            'ranked_duels_played' => 0,
        ]);
        $playerTwo = Player::factory()->create([
            'nmpz_rating' => 1000,
            'moving_rating' => 1000,
            'ranked_duels_played' => 0,
        ]);

        Http::fake([
            '*' => Http::response($this->contents),
        ]);

        new GetGamesPlayed(0)->handle();

        $this->assertDatabaseHas('ranked_games_scanned_user_ids', [
            'user_ids' => json_encode([$player->user_id]),
        ]);

        new GetGamesPlayed(1)->handle();

        $this->assertDatabaseHas('ranked_games_scanned_user_ids', [
            'user_ids' => json_encode([$player->user_id, $playerTwo->user_id]),
        ]);
    }

    public function test_it_creates_new_ranked_game_scanned_user_ids_if_no_players_match_query()
    {
        $this->assertDatabaseEmpty('ranked_games_scanned_user_ids');

        $player = Player::factory()->create([
            'nmpz_rating' => 1000,
            'moving_rating' => 1000,
            'ranked_duels_played' => 0,
        ]);
        $playerTwo = Player::factory()->create([
            'nmpz_rating' => 1000,
            'moving_rating' => 1000,
            'ranked_duels_played' => 0,
        ]);

        RankedGamesScannedUserIds::query()->create([
            'user_ids' => [$player->user_id, $playerTwo->user_id],
        ]);

        Http::fake([
            '*' => Http::response($this->contents),
        ]);

        new GetGamesPlayed(1)->handle();

        $this->assertDatabaseCount('ranked_games_scanned_user_ids', 2);
        $this->assertDatabaseHas('ranked_games_scanned_user_ids', [
            'user_ids' => json_encode([$player->user_id]),
        ]);
    }
}
