import {
    isTeam,
    type LeaderboardRow,
    type Player,
    type Team,
} from "@/Types/core.ts";

export enum CountryCode {
    ad = "ad",
    ae = "ae",
    af = "af",
    ag = "ag",
    ai = "ai",
    al = "al",
    am = "am",
    ao = "ao",
    ar = "ar",
    as = "as",
    at = "at",
    au = "au",
    aw = "aw",
    ax = "ax",
    az = "az",
    ba = "ba",
    bb = "bb",
    bd = "bd",
    be = "be",
    bf = "bf",
    bg = "bg",
    bh = "bh",
    bi = "bi",
    bj = "bj",
    bl = "bl",
    bm = "bm",
    bn = "bn",
    bo = "bo",
    bq = "bq",
    br = "br",
    bs = "bs",
    bt = "bt",
    bv = "bv",
    bw = "bw",
    by = "by",
    bz = "bz",
    ca = "ca",
    cc = "cc",
    cd = "cd",
    cf = "cf",
    cg = "cg",
    ch = "ch",
    ci = "ci",
    ck = "ck",
    cl = "cl",
    cm = "cm",
    cn = "cn",
    co = "co",
    cr = "cr",
    cu = "cu",
    cv = "cv",
    cw = "cw",
    cx = "cx",
    cy = "cy",
    cz = "cz",
    de = "de",
    dj = "dj",
    dk = "dk",
    dm = "dm",
    do = "do",
    dz = "dz",
    ec = "ec",
    ee = "ee",
    eg = "eg",
    eh = "eh",
    er = "er",
    es = "es",
    et = "et",
    fi = "fi",
    fj = "fj",
    fk = "fk",
    fm = "fm",
    fo = "fo",
    fr = "fr",
    ga = "ga",
    gb = "gb",
    gd = "gd",
    ge = "ge",
    gf = "gf",
    gg = "gg",
    gh = "gh",
    gi = "gi",
    gl = "gl",
    gm = "gm",
    gn = "gn",
    gp = "gp",
    gq = "gq",
    gr = "gr",
    gs = "gs",
    gt = "gt",
    gu = "gu",
    gw = "gw",
    gy = "gy",
    hk = "hk",
    hm = "hm",
    hn = "hn",
    hr = "hr",
    ht = "ht",
    hu = "hu",
    id = "id",
    ie = "ie",
    il = "il",
    im = "im",
    in = "in",
    io = "io",
    iq = "iq",
    ir = "ir",
    is = "is",
    it = "it",
    je = "je",
    jm = "jm",
    jo = "jo",
    jp = "jp",
    ke = "ke",
    kg = "kg",
    kh = "kh",
    ki = "ki",
    km = "km",
    kn = "kn",
    kp = "kp",
    kr = "kr",
    kw = "kw",
    ky = "ky",
    kz = "kz",
    xk = "xk",
    la = "la",
    lb = "lb",
    lc = "lc",
    li = "li",
    lk = "lk",
    lr = "lr",
    ls = "ls",
    lt = "lt",
    lu = "lu",
    lv = "lv",
    ly = "ly",
    ma = "ma",
    mc = "mc",
    md = "md",
    me = "me",
    mf = "mf",
    mg = "mg",
    mh = "mh",
    mk = "mk",
    ml = "ml",
    mm = "mm",
    mn = "mn",
    mo = "mo",
    mp = "mp",
    mq = "mq",
    mr = "mr",
    ms = "ms",
    mt = "mt",
    mu = "mu",
    mv = "mv",
    mw = "mw",
    mx = "mx",
    my = "my",
    mz = "mz",
    na = "na",
    nc = "nc",
    ne = "ne",
    nf = "nf",
    ng = "ng",
    ni = "ni",
    nl = "nl",
    no = "no",
    np = "np",
    nr = "nr",
    nu = "nu",
    nz = "nz",
    om = "om",
    pa = "pa",
    pe = "pe",
    pf = "pf",
    pg = "pg",
    ph = "ph",
    pk = "pk",
    pl = "pl",
    pm = "pm",
    pn = "pn",
    pr = "pr",
    ps = "ps",
    pt = "pt",
    pw = "pw",
    py = "py",
    qa = "qa",
    re = "re",
    ro = "ro",
    rs = "rs",
    xs = "xs",
    ru = "ru",
    rw = "rw",
    sa = "sa",
    sb = "sb",
    sc = "sc",
    sd = "sd",
    se = "se",
    sg = "sg",
    sh = "sh",
    si = "si",
    sj = "sj",
    sk = "sk",
    sl = "sl",
    sm = "sm",
    sn = "sn",
    so = "so",
    sr = "sr",
    ss = "ss",
    st = "st",
    sv = "sv",
    sx = "sx",
    sy = "sy",
    sz = "sz",
    tc = "tc",
    td = "td",
    tf = "tf",
    tg = "tg",
    th = "th",
    tj = "tj",
    tk = "tk",
    tl = "tl",
    tm = "tm",
    tn = "tn",
    to = "to",
    tr = "tr",
    tt = "tt",
    tv = "tv",
    tw = "tw",
    tz = "tz",
    ua = "ua",
    ug = "ug",
    um = "um",
    us = "us",
    uy = "uy",
    uz = "uz",
    va = "va",
    vc = "vc",
    ve = "ve",
    vg = "vg",
    vi = "vi",
    vn = "vn",
    vu = "vu",
    wf = "wf",
    ws = "ws",
    ye = "ye",
    yt = "yt",
    za = "za",
    zm = "zm",
    zw = "zw",
}

export const countryMap: Record<CountryCode, string> = {
    ad: "Andorra",
    ae: "United Arab Emirates",
    af: "Afghanistan",
    ag: "Antigua and Barbuda",
    ai: "Anguilla",
    al: "Albania",
    am: "Armenia",
    ao: "Angola",
    ar: "Argentina",
    as: "American Samoa",
    at: "Austria",
    au: "Australia",
    aw: "Aruba",
    ax: "Åland Islands",
    az: "Azerbaijan",
    ba: "Bosnia and Herzegovina",
    bb: "Barbados",
    bd: "Bangladesh",
    be: "Belgium",
    bf: "Burkina Faso",
    bg: "Bulgaria",
    bh: "Bahrain",
    bi: "Burundi",
    bj: "Benin",
    bl: "Saint Barthélemy",
    bm: "Bermuda",
    bn: "Brunei",
    bo: "Bolivia",
    bq: "Bonaire",
    br: "Brazil",
    bs: "Bahamas",
    bt: "Bhutan",
    bv: "Bouvet Island",
    bw: "Botswana",
    by: "Belarus",
    bz: "Belize",
    ca: "Canada",
    cc: "Cocos Islands",
    cd: "DRC",
    cf: "Central African Republic",
    cg: "Congo",
    ch: "Switzerland",
    ci: "Côte d'Ivoire",
    ck: "Cook Islands",
    cl: "Chile",
    cm: "Cameroon",
    cn: "China",
    co: "Colombia",
    cr: "Costa Rica",
    cu: "Cuba",
    cv: "Cabo Verde",
    cw: "Curaçao",
    cx: "Christmas Island",
    cy: "Cyprus",
    cz: "Czechia",
    de: "Germany",
    dj: "Djibouti",
    dk: "Denmark",
    dm: "Dominica",
    do: "Dominican Republic",
    dz: "Algeria",
    ec: "Ecuador",
    ee: "Estonia",
    eg: "Egypt",
    eh: "Western Sahara",
    er: "Eritrea",
    es: "Spain",
    et: "Ethiopia",
    fi: "Finland",
    fj: "Fiji",
    fk: "Falkland Islands",
    fm: "Micronesia",
    fo: "Faroe Islands",
    fr: "France",
    ga: "Gabon",
    gb: "United Kingdom",
    gd: "Grenada",
    ge: "Georgia",
    gf: "French Guiana",
    gg: "Guernsey",
    gh: "Ghana",
    gi: "Gibraltar",
    gl: "Greenland",
    gm: "Gambia",
    gn: "Guinea",
    gp: "Guadeloupe",
    gq: "Equatorial Guinea",
    gr: "Greece",
    gs: "South Georgia & SSI",
    gt: "Guatemala",
    gu: "Guam",
    gw: "Guinea-Bissau",
    gy: "Guyana",
    hk: "Hong Kong",
    hm: "Heard and McDonald Islands",
    hn: "Honduras",
    hr: "Croatia",
    ht: "Haiti",
    hu: "Hungary",
    id: "Indonesia",
    ie: "Ireland",
    il: "Israel",
    im: "Isle of Man",
    in: "India",
    io: "British Indian Ocean Territory",
    iq: "Iraq",
    ir: "Iran",
    is: "Iceland",
    it: "Italy",
    je: "Jersey",
    jm: "Jamaica",
    jo: "Jordan",
    jp: "Japan",
    ke: "Kenya",
    kg: "Kyrgyzstan",
    kh: "Cambodia",
    ki: "Kiribati",
    km: "Comoros",
    kn: "Saint Kitts and Nevis",
    kp: "North Korea",
    kr: "South Korea",
    kw: "Kuwait",
    ky: "Cayman Islands",
    kz: "Kazakhstan",
    xk: "Kosovo",
    la: "Laos",
    lb: "Lebanon",
    lc: "Saint Lucia",
    li: "Liechtenstein",
    lk: "Sri Lanka",
    lr: "Liberia",
    ls: "Lesotho",
    lt: "Lithuania",
    lu: "Luxembourg",
    lv: "Latvia",
    ly: "Libya",
    ma: "Morocco",
    mc: "Monaco",
    md: "Moldova",
    me: "Montenegro",
    mf: "Saint Martin",
    mg: "Madagascar",
    mh: "Marshall Islands",
    mk: "North Macedonia",
    ml: "Mali",
    mm: "Myanmar",
    mn: "Mongolia",
    mo: "Macao",
    mp: "Northern Mariana Islands",
    mq: "Martinique",
    mr: "Mauritania",
    ms: "Montserrat",
    mt: "Malta",
    mu: "Mauritius",
    mv: "Maldives",
    mw: "Malawi",
    mx: "Mexico",
    my: "Malaysia",
    mz: "Mozambique",
    na: "Namibia",
    nc: "New Caledonia",
    ne: "Niger",
    nf: "Norfolk Island",
    ng: "Nigeria",
    ni: "Nicaragua",
    nl: "Netherlands",
    no: "Norway",
    np: "Nepal",
    nr: "Nauru",
    nu: "Niue",
    nz: "New Zealand",
    om: "Oman",
    pa: "Panama",
    pe: "Peru",
    pf: "French Polynesia",
    pg: "Papua New Guinea",
    ph: "Philippines",
    pk: "Pakistan",
    pl: "Poland",
    pm: "Saint Pierre and Miquelon",
    pn: "Pitcairn",
    pr: "Puerto Rico",
    ps: "Palestine, State of",
    pt: "Portugal",
    pw: "Palau",
    py: "Paraguay",
    qa: "Qatar",
    re: "Réunion",
    ro: "Romania",
    rs: "Serbia",
    xs: "Serbia",
    ru: "Russia",
    rw: "Rwanda",
    sa: "Saudi Arabia",
    sb: "Solomon Islands",
    sc: "Seychelles",
    sd: "Sudan",
    se: "Sweden",
    sg: "Singapore",
    sh: "Saint Helena",
    si: "Slovenia",
    sj: "Svalbard and Jan Mayen",
    sk: "Slovakia",
    sl: "Sierra Leone",
    sm: "San Marino",
    sn: "Senegal",
    so: "Somalia",
    sr: "Suriname",
    ss: "South Sudan",
    st: "Sao Tome and Principe",
    sv: "El Salvador",
    sx: "Sint Maarten",
    sy: "Syria",
    sz: "Eswatini",
    tc: "Turks and Caicos Islands",
    td: "Chad",
    tf: "French Southern Territories",
    tg: "Togo",
    th: "Thailand",
    tj: "Tajikistan",
    tk: "Tokelau",
    tl: "Timor-Leste",
    tm: "Turkmenistan",
    tn: "Tunisia",
    to: "Tonga",
    tr: "Turkey",
    tt: "Trinidad and Tobago",
    tv: "Tuvalu",
    tw: "Taiwan",
    tz: "Tanzania",
    ua: "Ukraine",
    ug: "Uganda",
    um: "US Minor Islands",
    us: "United States",
    uy: "Uruguay",
    uz: "Uzbekistan",
    va: "Vatican City",
    vc: "Saint Vincent & the Grenadines",
    ve: "Venezuela",
    vg: "Virgin Islands, British",
    vi: "Virgin Islands, U.S.",
    vn: "Viet Nam",
    vu: "Vanuatu",
    wf: "Wallis and Futuna",
    ws: "Samoa",
    ye: "Yemen",
    yt: "Mayotte",
    za: "South Africa",
    zm: "Zambia",
    zw: "Zimbabwe",
};

export function usePlayerUtils() {
    const getFlagEmoji = (countryCode: string) => {
        if (!countryCode || countryCode.length !== 2) {
            return "🏴";
        }

        try {
            return String.fromCodePoint(
                ...countryCode
                    .toUpperCase()
                    .split("")
                    .map((char: string) => 127397 + char.charCodeAt(0)),
            );
        } catch {
            return "🏴";
        }
    };

    const getFlagImg = (countryCode: string, size = "24x18") => {
        return `https://flagcdn.com/${size}/${countryCode}.png`;
    };

    const generateProfileUrl = (id: string) => {
        return `https://www.geoguessr.com/user/${id}`;
    };

    const getCountryName = (countryCode: CountryCode) => {
        return countryMap[countryCode];
    };

    const rateableToLeaderboardRows = (
        playerOrTeam: Player | Team,
    ): LeaderboardRow =>
        isTeam(playerOrTeam)
            ? {
                  id: playerOrTeam.id,
                  geoGuessrId: playerOrTeam.team_id,
                  name: playerOrTeam.name,
                  rating: playerOrTeam.rating,
                  moving_rating: null,
                  no_move_rating: null,
                  nmpz_rating: null,
                  countryCodes: [
                      playerOrTeam.player_a.country_code,
                      playerOrTeam.player_b.country_code,
                  ],
                  players: [playerOrTeam.player_a, playerOrTeam.player_b],
                  isPlaceholder: false,
                  type: "team",
              }
            : {
                  id: playerOrTeam.id,
                  geoGuessrId: playerOrTeam.user_id,
                  name: playerOrTeam.name,
                  rating: playerOrTeam.rating,
                  moving_rating: playerOrTeam.moving_rating,
                  no_move_rating: playerOrTeam.no_move_rating,
                  nmpz_rating: playerOrTeam.nmpz_rating,
                  countryCodes: [playerOrTeam.country_code],
                  isPlaceholder: false,
                  type: "player",
              };

    return {
        getFlagEmoji,
        generateProfileUrl,
        getCountryName,
        getFlagImg,
        rateableToLeaderboardRows,
        countryMap,
    };
}
