name: Run PHPUnit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build containers
        run: |
          export WWWUSER=1337
          export WWWGROUP=1337
          export DB_DATABASE=laravel
          export DB_USERNAME=sail
          export DB_PASSWORD=password
          docker compose build

      - name: Start containers
        run: docker compose up -d

      - name: Copy env file
        run: docker compose exec -T laravel.test cp .env.example .env

      - name: Generate key
        run: docker compose exec -T laravel.test php artisan key:generate

      - name: Wait for Postgres
        run: |
          for i in {1..30}; do
            if docker compose exec -T pgsql pg_isready -U sail -d laravel; then
              exit 0
            fi
            sleep 2
          done
          exit 1

      - name: Run migrations
        run: docker compose exec -T laravel.test php artisan migrate --env=testing --force

      - name: Run tests
        run: docker compose exec -T laravel.test php artisan test --env=testing
