<?php

namespace Feature\Controllers;

use App\Models\Player;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Config;
use Tests\TestCase;

class GetCountryAverageRatingsTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        Config::set('geo.minimum_average_country_players', 10);

        Player::factory()->count(10)->create(['country_code' => 'ca']);
        Player::factory()->count(10)->create(['country_code' => 'us']);
        Player::factory()->count(10)->create(['country_code' => 'de']);
    }

    public function test_it_returns_country_average_ratings()
    {
        $response = $this->getJson('country-average-ratings');
        $response->assertOk();

        $response->assertJson([
            'data' => [
                'ca' => Player::query()->where('country_code', 'ca')->avg('rating'),
                'us' => Player::query()->where('country_code', 'us')->avg('rating'),
                'de' => Player::query()->where('country_code', 'de')->avg('rating'),
            ],
        ]);
    }

    /**
     * @dataProvider provideGamemodes
     */
    public function test_it_returns_country_average_ratings_for_gamemodes($gamemode)
    {
        $response = $this->getJson('country-average-ratings?gamemode=' . $gamemode);
        $response->assertOk();

        $response->assertJson([
            'data' => [
                'ca' => Player::query()->where('country_code', 'ca')->avg($gamemode . '_rating'),
                'us' => Player::query()->where('country_code', 'us')->avg($gamemode . '_rating'),
                'de' => Player::query()->where('country_code', 'de')->avg($gamemode . '_rating'),
            ],
        ]);
    }

    public static function provideGamemodes(): array
    {
        return [
            ['gamemode' => 'moving'],
            ['gamemode' => 'no_move'],
            ['gamemode' => 'nmpz'],
        ];
    }
}
